# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='com.dealicious.grpc',
  syntax='proto3',
  serialized_options=b'B\tGrpcModelZ\025com.deali/golang-grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngrpc.proto\x12\x13\x63om.dealicious.grpc\"j\n\x07Request\x12\x13\n\x0bstringValue\x18\x01 \x01(\t\x12\x11\n\tlongValue\x18\x02 \x01(\x04\x12\x37\n\x0c\x63ustomObject\x18\x03 \x01(\x0b\x32!.com.dealicious.grpc.CustomObject\"#\n\x0c\x43ustomObject\x12\x13\n\x0b\x63ustomValue\x18\x01 \x01(\x05\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x03(\x01\x32\xc7\x02\n\x0bGrpcService\x12G\n\x06getOne\x12\x1c.com.dealicious.grpc.Request\x1a\x1d.com.dealicious.grpc.Response\"\x00\x12O\n\x0cserverStream\x12\x1c.com.dealicious.grpc.Request\x1a\x1d.com.dealicious.grpc.Response\"\x00\x30\x01\x12O\n\x0c\x63lientStream\x12\x1c.com.dealicious.grpc.Request\x1a\x1d.com.dealicious.grpc.Response\"\x00(\x01\x12M\n\x08\x62iStream\x12\x1c.com.dealicious.grpc.Request\x1a\x1d.com.dealicious.grpc.Response\"\x00(\x01\x30\x01\x42\"B\tGrpcModelZ\x15\x63om.deali/golang-grpcb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='com.dealicious.grpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stringValue', full_name='com.dealicious.grpc.Request.stringValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longValue', full_name='com.dealicious.grpc.Request.longValue', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customObject', full_name='com.dealicious.grpc.Request.customObject', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=141,
)


_CUSTOMOBJECT = _descriptor.Descriptor(
  name='CustomObject',
  full_name='com.dealicious.grpc.CustomObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customValue', full_name='com.dealicious.grpc.CustomObject.customValue', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=178,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='com.dealicious.grpc.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='com.dealicious.grpc.Response.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=205,
)

_REQUEST.fields_by_name['customObject'].message_type = _CUSTOMOBJECT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['CustomObject'] = _CUSTOMOBJECT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:com.dealicious.grpc.Request)
  })
_sym_db.RegisterMessage(Request)

CustomObject = _reflection.GeneratedProtocolMessageType('CustomObject', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMOBJECT,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:com.dealicious.grpc.CustomObject)
  })
_sym_db.RegisterMessage(CustomObject)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:com.dealicious.grpc.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_GRPCSERVICE = _descriptor.ServiceDescriptor(
  name='GrpcService',
  full_name='com.dealicious.grpc.GrpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=535,
  methods=[
  _descriptor.MethodDescriptor(
    name='getOne',
    full_name='com.dealicious.grpc.GrpcService.getOne',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='serverStream',
    full_name='com.dealicious.grpc.GrpcService.serverStream',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='clientStream',
    full_name='com.dealicious.grpc.GrpcService.clientStream',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='biStream',
    full_name='com.dealicious.grpc.GrpcService.biStream',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCSERVICE)

DESCRIPTOR.services_by_name['GrpcService'] = _GRPCSERVICE

# @@protoc_insertion_point(module_scope)
